import { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { Providers } from './providers';

const poppins = Poppins({ subsets: ['latin'], weight: ['100', '200', '300', '400' ,'500', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (      
    <html lang="pt-br">
      <body className={poppins.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
